# Generated by Django 3.0.6 on 2020-05-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('workout_type', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coaches.Coach')),
            ],
        ),
    ]
