# Generated by Django 3.0.6 on 2020-05-12 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 12, 12, 18, 23, 587072)),
        ),
    ]
