# Generated by Django 3.0.6 on 2020-05-12 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200512_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='list_date',
        ),
        migrations.AddField(
            model_name='class',
            name='class_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 12, 12, 33, 32, 139396)),
        ),
    ]
