# Generated by Django 3.0.6 on 2020-05-12 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20200512_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 12, 18, 26, 15, 953601)),
        ),
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(upload_to='classes/%Y/%m/%d'),
        ),
    ]
