# Generated by Django 3.0.6 on 2020-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0046_auto_20200525_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_date',
        ),
        migrations.AddField(
            model_name='class',
            name='month',
            field=models.CharField(choices=[('1', 'JANUARY'), ('2', 'FEBRUARY'), ('3', 'MAR')], default='1', max_length=2),
        ),
    ]
