# Generated by Django 3.0.6 on 2020-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0047_auto_20200530_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='month',
        ),
        migrations.AddField(
            model_name='class',
            name='fridayday',
            field=models.CharField(choices=[('1', '10-14'), ('2', '14-16'), ('3', '16-18'), ('4', '18-20'), ('5', '20-22'), ('6', 'closed')], default='6', max_length=2, verbose_name='جمعه'),
        ),
        migrations.AddField(
            model_name='class',
            name='monday',
            field=models.CharField(choices=[('1', '10-14'), ('2', '14-16'), ('3', '16-18'), ('4', '18-20'), ('5', '20-22'), ('6', 'closed')], default='6', max_length=2, verbose_name='دوشنبه'),
        ),
        migrations.AddField(
            model_name='class',
            name='saturday',
            field=models.CharField(choices=[('1', '10-14'), ('2', '14-16'), ('3', '16-18'), ('4', '18-20'), ('5', '20-22'), ('6', 'closed')], default='6', max_length=2, verbose_name='شنبه'),
        ),
        migrations.AddField(
            model_name='class',
            name='sunday',
            field=models.CharField(choices=[('1', '10-14'), ('2', '14-16'), ('3', '16-18'), ('4', '18-20'), ('5', '20-22'), ('6', 'closed')], default='6', max_length=2, verbose_name='یکشنبه'),
        ),
        migrations.AddField(
            model_name='class',
            name='thursday',
            field=models.CharField(choices=[('1', '10-14'), ('2', '14-16'), ('3', '16-18'), ('4', '18-20'), ('5', '20-22'), ('6', 'closed')], default='6', max_length=2, verbose_name='پنجشنبه'),
        ),
        migrations.AddField(
            model_name='class',
            name='tuesday',
            field=models.CharField(choices=[('1', '10-14'), ('2', '14-16'), ('3', '16-18'), ('4', '18-20'), ('5', '20-22'), ('6', 'closed')], default='6', max_length=2, verbose_name='سه شنبه'),
        ),
        migrations.AddField(
            model_name='class',
            name='wednesday',
            field=models.CharField(choices=[('1', '10-14'), ('2', '14-16'), ('3', '16-18'), ('4', '18-20'), ('5', '20-22'), ('6', 'closed')], default='6', max_length=2, verbose_name='چهارشنبه'),
        ),
    ]
