# Generated by Django 3.0.6 on 2020-05-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0048_auto_20200530_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='fridayday',
            field=models.CharField(choices=[('10-14', '10-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22'), ('closed', 'closed')], default='closed', max_length=10, verbose_name='جمعه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='monday',
            field=models.CharField(choices=[('10-14', '10-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22'), ('closed', 'closed')], default='closed', max_length=10, verbose_name='دوشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='saturday',
            field=models.CharField(choices=[('10-14', '10-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22'), ('closed', 'closed')], default='closed', max_length=10, verbose_name='شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='sunday',
            field=models.CharField(choices=[('10-14', '10-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22'), ('closed', 'closed')], default='closed', max_length=10, verbose_name='یکشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='thursday',
            field=models.CharField(choices=[('10-14', '10-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22'), ('closed', 'closed')], default='closed', max_length=10, verbose_name='پنجشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tuesday',
            field=models.CharField(choices=[('10-14', '10-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22'), ('closed', 'closed')], default='closed', max_length=10, verbose_name='سه شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='wednesday',
            field=models.CharField(choices=[('10-14', '10-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22'), ('closed', 'closed')], default='closed', max_length=10, verbose_name='چهارشنبه'),
        ),
    ]
