# Generated by Django 3.0.6 on 2020-06-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0049_auto_20200530_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='fridayday',
            new_name='friday',
        ),
    ]
