# Generated by Django 3.0.6 on 2020-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0050_auto_20200614_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='friday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='جمعه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='monday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='دوشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='saturday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='sunday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='یکشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='thursday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='پنجشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tuesday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='سه شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='wednesday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='چهارشنبه'),
        ),
    ]
