# Generated by Django 3.0.6 on 2020-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0051_auto_20200614_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='price',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10),
        ),
    ]
