# Generated by Django 3.0.6 on 2020-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0052_class_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
