# Generated by Django 3.0.5 on 2020-07-12 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0053_auto_20200616_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Online Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='live_stream_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='friday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='جمعه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(upload_to='classes/presence_classes/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='class',
            name='monday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='دوشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='saturday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='sunday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='یکشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='thursday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='پنجشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tuesday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='سه شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='wednesday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='چهارشنبه'),
        ),
    ]
