# Generated by Django 3.0.5 on 2020-07-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0007_auto_20200514_1952'),
        ('classes', '0054_auto_20200712_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Presence Classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='live_stream_link',
        ),
        migrations.AlterField(
            model_name='class',
            name='friday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='جمعه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='monday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='دوشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='saturday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='sunday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='یکشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='thursday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='پنجشنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tuesday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='سه شنبه'),
        ),
        migrations.AlterField(
            model_name='class',
            name='wednesday',
            field=models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('تعطیل', 'تعطیل')], default='تعطیل', max_length=100, verbose_name='چهارشنبه'),
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('workout_type', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='classes/online_classes/%Y/%m/%d')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('live_stream_link', models.URLField()),
                ('is_published', models.BooleanField(default=True)),
                ('sunday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='یکشنبه')),
                ('monday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='دوشنبه')),
                ('tuesday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='سه شنبه')),
                ('wednesday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='چهارشنبه')),
                ('thursday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='پنجشنبه')),
                ('friday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='جمعه')),
                ('saturday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='شنبه')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coaches.Coach')),
            ],
            options={
                'verbose_name_plural': 'Online Classes',
            },
        ),
    ]
