# Generated by Django 3.0.5 on 2020-07-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0055_auto_20200712_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclass',
            name='live_stream_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
