# Generated by Django 3.0.5 on 2020-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0056_auto_20200712_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='workout_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='workout_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
