# Generated by Django 3.0.5 on 2020-07-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0057_auto_20200712_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
