# Generated by Django 3.0.5 on 2020-07-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0007_auto_20200514_1952'),
        ('classes', '0058_auto_20200712_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateOnlineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('workout_type', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='classes/private_online_classes/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('live_stream_link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sunday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='یکشنبه')),
                ('monday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='دوشنبه')),
                ('tuesday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='سه شنبه')),
                ('wednesday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='چهارشنبه')),
                ('thursday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='پنجشنبه')),
                ('friday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='جمعه')),
                ('saturday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='شنبه')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coaches.Coach')),
            ],
            options={
                'verbose_name_plural': 'کلاس های انلاین خصوصی',
            },
        ),
        migrations.CreateModel(
            name='PublicOnlineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('workout_type', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='classes/public_online_classes/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('live_stream_link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sunday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='یکشنبه')),
                ('monday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='دوشنبه')),
                ('tuesday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='سه شنبه')),
                ('wednesday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='چهارشنبه')),
                ('thursday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='پنجشنبه')),
                ('friday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='جمعه')),
                ('saturday', models.CharField(choices=[('10:00-14:00', '10:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('افلاین', 'افلاین')], default='افلاین', max_length=100, verbose_name='شنبه')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coaches.Coach')),
            ],
            options={
                'verbose_name_plural': 'کلاس های انلاین عمومی',
            },
        ),
        migrations.DeleteModel(
            name='OnlineClass',
        ),
    ]
