# Generated by Django 3.0.5 on 2020-07-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0059_auto_20200712_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateonlineclass',
            name='live_stream_link',
        ),
        migrations.RemoveField(
            model_name='publiconlineclass',
            name='live_stream_link',
        ),
    ]
