# Generated by Django 3.0.6 on 2020-05-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banner'},
        ),
    ]
