# Generated by Django 3.0.6 on 2020-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200513_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='display_filter_id',
            field=models.IntegerField(default=1),
        ),
    ]
