# Generated by Django 3.0.5 on 2020-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200724_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='display_filter_id',
            field=models.CharField(choices=[('buffet', 'بوفه'), ('gym', 'محیط باشگاه'), ('یوگا', 'یوگا'), ('بادی پامپ', 'بادی پامپ'), ('بدنسازی', 'بدنسازی'), ('تی آر ایکس', 'تی آر ایکس'), ('اسپینینگ', 'اسپینینگ'), ('فیتنس', 'فیتنس')], max_length=200),
        ),
    ]
