# Generated by Django 3.0.6 on 2020-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d')),
                ('small_title', models.CharField(max_length=100)),
                ('normal_title', models.CharField(max_length=100)),
                ('highlighted_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('class_type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('Advantage_1', models.CharField(max_length=200)),
                ('Advantage_2', models.CharField(max_length=200)),
                ('Advantage_3', models.CharField(max_length=200)),
                ('Advantage_4', models.CharField(max_length=200)),
            ],
        ),
    ]
