# Generated by Django 3.0.6 on 2020-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='highlighted_title',
            new_name='highlighted_title_1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='normal_title',
            new_name='normal_title_1',
        ),
        migrations.AddField(
            model_name='banner',
            name='highlighted_title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='highlighted_title_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='normal_title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='normal_title_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
