# Generated by Django 3.0.6 on 2020-05-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200512_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='class_type',
        ),
        migrations.AddField(
            model_name='plan',
            name='month_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='banner',
            name='highlighted_title_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='normal_title_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='small_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Advantage_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Advantage_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Advantage_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Advantage_4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
