# Generated by Django 3.0.5 on 2020-07-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200513_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/carousel_banners/%Y/%m/%d')),
                ('small_title', models.CharField(blank=True, max_length=100)),
                ('normal_title_1', models.CharField(blank=True, max_length=100)),
                ('normal_title_2', models.CharField(blank=True, max_length=100)),
                ('normal_title_3', models.CharField(blank=True, max_length=100)),
                ('highlighted_title_1', models.CharField(blank=True, max_length=100)),
                ('highlighted_title_2', models.CharField(blank=True, max_length=100)),
                ('highlighted_title_3', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'بنر های خانه',
            },
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'بنر ها'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='highlighted_title_1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='highlighted_title_2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='highlighted_title_3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='normal_title_1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='normal_title_2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='normal_title_3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='small_title',
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('presence_class', 'کلاس های حضوری'), ('online_private_class', 'کلاس های انلاین خصوصی'), ('online_public_class', 'کلاس های انلاین عمومی'), ('beginner_workouts', 'تمرینات سطح مبتدی'), ('intermediate_workouts', 'تمرینات سطح متوسط'), ('advanced_workouts', 'تمرینات سطح پیشرفته'), ('our_team', 'تیم ما'), ('gallery', 'گالری'), ('contact_us', 'ارتباط با ما'), ('profile', 'پروفایل کاربری')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='banners/pages_banners/%Y/%m/%d'),
        ),
    ]
