# Generated by Django 3.0.5 on 2020-07-15 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200715_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='banners/pages_banners/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('presence_class', 'کلاس های حضوری'), ('online_private_class', 'کلاس های انلاین خصوصی'), ('online_public_class', 'کلاس های انلاین عمومی'), ('beginner_workouts', 'تمرینات سطح مبتدی'), ('intermediate_workouts', 'تمرینات سطح متوسط'), ('advanced_workouts', 'تمرینات سطح پیشرفته'), ('our_team', 'تیم ما'), ('gallery', 'گالری'), ('contact_us', 'ارتباط با ما'), ('profile', 'پروفایل کاربری')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
