# Generated by Django 3.0.5 on 2020-07-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200715_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('presence_class', 'کلاس های حضوری'), ('online_private_class', 'کلاس های انلاین خصوصی'), ('online_public_class', 'کلاس های انلاین عمومی'), ('beginner_workouts', 'تمرینات سطح مبتدی'), ('intermediate_workouts', 'تمرینات سطح متوسط'), ('advanced_workouts', 'تمرینات سطح پیشرفته'), ('our_team', 'تیم ما'), ('gallery', 'گالری'), ('contact_us', 'ارتباط با ما'), ('profile', 'پروفایل کاربری'), ('online_private_class_details', 'جزئیات کلاس انلاین خصوصی'), ('online_public_class_details', 'جزئیات کلاس انلاین عمومی'), ('presence_class_details', 'جزئیات کلاس حضوری')], max_length=100),
        ),
    ]
