# Generated by Django 3.0.5 on 2020-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_honors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honors',
            name='description',
            field=models.TextField(),
        ),
    ]
