# Generated by Django 4.1.3 on 2023-11-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200716_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='carouselbanner',
            options={'verbose_name_plural': 'Home Banners'},
        ),
        migrations.AlterModelOptions(
            name='honors',
            options={'verbose_name_plural': 'Club Honors'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('presence_class', 'In-Person Classes'), ('online_private_class', 'Online Private Classes'), ('online_public_class', 'Online Public Classes'), ('beginner_workouts', 'Beginner Workouts'), ('intermediate_workouts', 'Intermediate Workouts'), ('advanced_workouts', 'Advanced Workouts'), ('our_team', 'Our Team'), ('gallery', 'Gallery'), ('contact_us', 'Contact Us'), ('profile', 'Profile'), ('online_private_class_details', 'Online Private Class Details'), ('online_public_class_details', 'Online Public Class Details'), ('presence_class_details', 'In-Person Class Details')], max_length=100, unique=True),
        ),
    ]
