# Generated by Django 4.1.3 on 2023-11-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20200716_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestmarketing',
            options={'verbose_name_plural': 'Guest Marketing Emails'},
        ),
        migrations.AlterModelOptions(
            name='marketing',
            options={'verbose_name_plural': 'User Marketing Emails'},
        ),
        migrations.AlterField(
            model_name='marketing',
            name='mailchimp_subscribed',
            field=models.BooleanField(null=True),
        ),
    ]
