# Generated by Django 3.0.6 on 2020-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_billingprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
