# Generated by Django 3.0.6 on 2020-06-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0007_auto_20200629_1255'),
        ('accounts', '0006_auto_20200626_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingProfile',
        ),
    ]
