# Generated by Django 3.0.5 on 2020-07-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_billingprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
