# Generated by Django 3.0.6 on 2020-05-12 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='hire_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
