# Generated by Django 3.0.6 on 2020-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20200512_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(upload_to='coaches/%Y/%m/%d'),
        ),
    ]
