# Generated by Django 3.0.6 on 2020-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_auto_20200514_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='info',
        ),
        migrations.AddField(
            model_name='coach',
            name='info_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coach',
            name='info_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coach',
            name='info_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coach',
            name='info_4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
