# Generated by Django 3.0.6 on 2020-05-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_auto_20200514_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
    ]
