# Generated by Django 3.0.5 on 2020-07-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0012_coach_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='account',
        ),
    ]
