# Generated by Django 3.0.5 on 2020-07-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0060_auto_20200713_2033'),
        ('coaches', '0016_coach_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='class_type',
        ),
        migrations.AddField(
            model_name='coach',
            name='presence_classes',
            field=models.ManyToManyField(related_name='presence_classes', to='classes.Class'),
        ),
        migrations.AddField(
            model_name='coach',
            name='private_classes',
            field=models.ManyToManyField(related_name='private_classes', to='classes.PrivateOnlineClass'),
        ),
        migrations.AddField(
            model_name='coach',
            name='public_classes',
            field=models.ManyToManyField(related_name='public_classes', to='classes.PublicOnlineClass'),
        ),
    ]
