# Generated by Django 3.0.5 on 2020-07-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0060_auto_20200713_2033'),
        ('coaches', '0018_auto_20200713_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='presence_classes',
        ),
        migrations.AddField(
            model_name='coach',
            name='presence_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_classes', to='classes.Class'),
        ),
        migrations.RemoveField(
            model_name='coach',
            name='private_classes',
        ),
        migrations.AddField(
            model_name='coach',
            name='private_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_classes', to='classes.PrivateOnlineClass'),
        ),
        migrations.RemoveField(
            model_name='coach',
            name='public_classes',
        ),
        migrations.AddField(
            model_name='coach',
            name='public_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_classes', to='classes.PublicOnlineClass'),
        ),
    ]
