# Generated by Django 3.0.5 on 2020-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0020_auto_20200714_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='live_stream_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
