# Generated by Django 3.0.5 on 2020-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0022_auto_20200714_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='classes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
