# Generated by Django 3.0.5 on 2020-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0023_coach_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='classes',
            field=models.TextField(blank=True),
        ),
    ]
