# Generated by Django 3.0.5 on 2020-07-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0025_auto_20200714_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'مربیان'},
        ),
    ]
