# Generated by Django 3.0.5 on 2020-07-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0026_auto_20200715_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='account',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='age',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='height',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='weight',
        ),
    ]
