# Generated by Django 3.0.5 on 2020-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0027_auto_20200721_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='classes',
            field=models.TextField(blank=True),
        ),
    ]
