# Generated by Django 4.1.3 on 2023-11-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0028_auto_20200725_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
    ]
