# Generated by Django 3.0.6 on 2020-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_info',
            options={'verbose_name_plural': 'Informations'},
        ),
        migrations.AddField(
            model_name='contact_info',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_info',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
