# Generated by Django 3.0.5 on 2020-07-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_auto_20200709_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='contact_info',
            options={'verbose_name_plural': 'Website information'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Messages'},
        ),
    ]
