# Generated by Django 4.1.3 on 2023-11-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0007_message_is_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_info',
            options={'verbose_name_plural': 'Website Information'},
        ),
    ]
