# Generated by Django 3.0.6 on 2020-06-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'بنر',
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rule', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='workout/workouts/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'تمرینات',
            },
        ),
        migrations.CreateModel(
            name='Workout_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='workout/workout_list/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('workout1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout1', to='workouts.Workouts')),
                ('workout10', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout10', to='workouts.Workouts')),
                ('workout11', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout11', to='workouts.Workouts')),
                ('workout12', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout12', to='workouts.Workouts')),
                ('workout13', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout13', to='workouts.Workouts')),
                ('workout14', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout14', to='workouts.Workouts')),
                ('workout15', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout15', to='workouts.Workouts')),
                ('workout16', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout16', to='workouts.Workouts')),
                ('workout17', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout17', to='workouts.Workouts')),
                ('workout18', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout18', to='workouts.Workouts')),
                ('workout19', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout19', to='workouts.Workouts')),
                ('workout2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout2', to='workouts.Workouts')),
                ('workout20', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout20', to='workouts.Workouts')),
                ('workout3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout3', to='workouts.Workouts')),
                ('workout4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout4', to='workouts.Workouts')),
                ('workout5', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout5', to='workouts.Workouts')),
                ('workout6', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout6', to='workouts.Workouts')),
                ('workout7', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout7', to='workouts.Workouts')),
                ('workout8', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout8', to='workouts.Workouts')),
                ('workout9', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout9', to='workouts.Workouts')),
            ],
            options={
                'verbose_name_plural': 'فهرست تمرینات',
            },
        ),
    ]
