# Generated by Django 3.0.6 on 2020-06-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_list',
            name='grade',
            field=models.CharField(choices=[('مبتدی', 'مبتدی'), ('متوسط', 'متوسط'), ('پیشرفته', 'پیشرفته')], max_length=200),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout1', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout10', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout11', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout12', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout13', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout14', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout15', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout16', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout17', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout18', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout19', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout2', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout20', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout3', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout4', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout5', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout6', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout7', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout8', to='workouts.Workouts'),
        ),
        migrations.AlterField(
            model_name='workout_list',
            name='workout9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout9', to='workouts.Workouts'),
        ),
    ]
