# Generated by Django 3.0.6 on 2020-07-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20200613_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_list',
            name='workout1',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout10',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout11',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout12',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout13',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout14',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout15',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout16',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout17',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout18',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout19',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout2',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout20',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout3',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout4',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout5',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout6',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout7',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout8',
        ),
        migrations.RemoveField(
            model_name='workout_list',
            name='workout9',
        ),
        migrations.AddField(
            model_name='workout_list',
            name='workouts',
            field=models.ManyToManyField(blank=True, null=True, to='workouts.Workouts'),
        ),
    ]
