# Generated by Django 3.0.6 on 2020-07-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200703_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout_list',
            old_name='workouts',
            new_name='selected_workouts',
        ),
    ]
