# Generated by Django 3.0.6 on 2020-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20200703_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_list',
            name='selected_workouts',
            field=models.ManyToManyField(blank=True, to='workouts.Workouts'),
        ),
    ]
