# Generated by Django 3.0.5 on 2020-07-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20200704_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
