# Generated by Django 3.0.6 on 2020-06-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('پرداخت شده', 'پرداخت شده'), ('لغو شده', 'لغو شده')], default='ایجاد شده', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Cart')),
            ],
        ),
    ]
