# Generated by Django 3.0.6 on 2020-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='shippment_total',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=100),
        ),
    ]
