# Generated by Django 3.0.6 on 2020-06-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_register_shippment_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='shippment_total',
        ),
    ]
