# Generated by Django 3.0.6 on 2020-06-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200626_1854'),
        ('registers', '0005_remove_register_shippment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='register',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.BillingProfile'),
        ),
    ]
