# Generated by Django 3.0.5 on 2020-07-07 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0007_auto_20200629_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
