# Generated by Django 3.0.5 on 2020-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0008_register_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
