# Generated by Django 3.0.5 on 2020-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0010_auto_20200707_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
