# Generated by Django 3.0.5 on 2020-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_auto_20200707_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='register_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
