# Generated by Django 3.0.5 on 2020-07-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_register_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='active',
        ),
    ]
