# Generated by Django 3.0.5 on 2020-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0013_remove_register_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
