# Generated by Django 3.0.5 on 2020-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0014_register_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('پرداخت شده', 'پرداخت شده')], default='ایجاد شده', max_length=120),
        ),
    ]
