# Generated by Django 3.0.5 on 2020-07-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0015_auto_20200710_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'ثبت نام ها'},
        ),
    ]
