# Generated by Django 3.0.5 on 2020-07-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
