# Generated by Django 3.0.5 on 2020-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0059_auto_20200712_1228'),
        ('cart', '0004_remove_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='online_selected_class',
            field=models.ManyToManyField(blank=True, to='classes.PrivateOnlineClass'),
        ),
    ]
