# Generated by Django 3.0.5 on 2020-07-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_online_selected_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'کلاس های درخواست شده برای ثبت نام'},
        ),
    ]
