# Generated by Django 4.1.3 on 2023-11-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200716_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Requested Classes for Registration'},
        ),
    ]
